### ISSUE TITLE
Fallo en job de limpieza borrando archivos en carpeta raíz

### ISSUE THREAD

**Issue by ja-garcia** [carm-es/inside#16]
El job `temporalDataCleanInsideTrigger` está fallando al hacer el borrado de la carpeta temporal definida en _-DtmpShared.path_= cuando existen ficheros directamente en la raíz de la mencionada carpeta (interpreta que todos son directorios y salta una excepción java.lang.NullPointerException).

**Comment by ja-garcia** [comment]
Resuelto en abcc1b26155b9ba2f43b82d51c7a1510320a7a1c

**Comment by marpegaso** [comment]
Revisando todos los issues de este proyecto para su posible aplicación en la nueva versión 2.0.8 hemos podido comprobar que **este issue no sería necesario** realizarlo. Configurando un **nuevo directorio** llamado **temporal** dentro de **${CATALINA_BASE}/datos** y poniendo la propiedad correspondiente del fichero **loadTables-config.properties** con este valor Path.temp=**${tmpShared.path}/temporal** debería funcionar correctamente. En el fichero **temporalData.properties** dejaríamos como está la propiedad temporalData.path=**${tmpShared.path}**

**Comment by alp23g** [comment]
En el repositorio interno [inside](https://gitlab.carm.es/SIAC/PAECARM/inside) de GITLAB que tenemos para la versión 2.0.8 en DESarrollo quedó resuelto este asunto, sin necesidad de parchear el código de INSIDE. Nos tuvieron que ayudar los compañeros de Sistemas para resolver el problema, está documenado en el ticket de GLPI [571135](https://glpi.carm.es/front/ticket.form.php?id=571135)
