### ISSUE TITLE
Detectamos Error en sandra-pro al invocar a Eeutil-Oper-Firma en Inside apellido2

### ISSUE THREAD

**Issue by alp23g** [carm-es/inside#18]
[SGAD 559166](https://ssweb.seap.minhap.es/ayuda/seguimiento). Nos dimos cuenta nosotros mismos mirando los errores con Kibana. Primero pusimos la solicitud de ayuda al Estado a la SGAD. Las credenciales de acceso las guardo en la documentación interna en el proyecto inside-carm-config.
[GLPI 597760](https://glpi.carm.es/front/ticket.form.php?id=597760&). Posteriormente ha llegado la incidencia. Y lo último que he hecho ha sido crear este issue y mover todos los files que he ido recopilando (info.odt, .xml de petición y respuesta etc.) los coloco en la documentación en el proyecto interno en "**directorioBase\inside-carm-config\documentacion\#18 Detectamos Error en sandra-pro al invocar a Eeutil-Oper-Firma en Inside apellido2**"

El día 12/06/19 me he fijado en que habían 3 momentos en los que se han producido 3 errores seguidos (en total 9 errores) en SANDRA (y en INSIDE) y es que PRESENTADOR hace 3 reintentos en cada presentación.

Además, parece ser que un ciudadano ha puesto una queja porque no le dejaba presentar una solicitud firmada con un certificado "raro" de los de representante, que lleva los dos apellidos en el surname... Podría tener relación, pero no hemos encontrado cuándo fue la presentación.

Este es el **extracto del log** de un caso cualquiera:

10:15:27,836 ERROR InfoFirmaServiceImpl:153 - Excepción en la llamada al WS de obtención de **Información de Firma**
javax.xml.ws.soap.SOAPFaultException: Marshalling Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'fecha'. One of '{apellido2}' is expected.
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:156)
	at com.sun.proxy.$Proxy78.obtenerInformacionFirma(Unknown Source)
	at es.mpt.dsic.infofirma.service.impl.InfoFirmaServiceImpl.getInfoFirma(InfoFirmaServiceImpl.java:129)
...
Caused by: org.apache.cxf.binding.soap.SoapFault: Marshalling Error: cvc-complex-type.2.4.a: **Invalid content was found starting with element 'fecha'. One of '{apellido2}' is expected**.
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.unmarshalFault(Soap11FaultInInterceptor.java:75)
...

Y en el elastic ésto es lo que le corresponde:
          "aplicacion" : "PRESENTADOR",
          "servicio" : "altaDocumentoOriginal",
          "procedimiento" : 1001,
          "documento" : "DI005",
          "duracion" : 1128,
          "error" : "400",
          "@timestamp" : 1560327327866, Wed Jun 12 2019 10:15:27
          "departamento" : 431,
          "referenciaorigen" : "1001-0000000320/Nfaz",
          "texto_mensaje" : "Error en la petición a Inside :  El documento contiene una firma inválida o desconocida"

Hemos podido comprobar qué clase fallaba y en qué línea exactamente, era la **129** de la clase **C:\EA\gitCarmEs\inside\infofirma-service\src\main\java\es\mpt\dsic\infofirma\service\impl\InfoFirmaServiceImpl.java**
Y ésta es esa línea: InformacionFirma infoFirma = port.**obtenerInformacionFirma**(applicationLogin, dataHanlerFirma, opcionesWS, dataHanlerFirmaContenido);

- [x] Pongo una consulta en https://ssweb.seap.minhap.es/ayuda/consulta/SuiteInside
Asunto: **Error al validar firma en Eeutil-Oper-Firma certificado sin apellido2**
Tipo: Fallo o Error en Servicios Web

- [x] En el caso de que no nos arreglen este problema de Error en sandra-pro al invocar a Eeutil-Oper-Firma en Inside apellido2, una opción sería deshabilitar en INSIDE la comprobación de la firma en los documentos originales. **No ha funcionado, no nos sirve esta opción**. Los documentos asociados a este TEST que he realizado están en "**directorioBase\inside-carm-config\documentacion\#18 Detectamos Error en sandra-pro al invocar a Eeutil-Oper-Firma en Inside apellido2\Documentos Test**"

En la documentación en el proyecto interno en "**directorioBase\inside-carm-config\documentacion\\#18 Detectamos Error en sandra-pro al invocar a Eeutil-Oper-Firma en Inside apellido2**" hay mucha más información de lo que está ocurriendo, también en el GLPI y en la consulta enviada a la SGAD, ya que he tenido que intercambiar sucesivos mensajes con ellos para poder identificar el problema.

El día 19/08/19 desde el MHAP nos envían email de disculpas acerca del retraso en la resolución de las incidencias en general y con ésta en particular: **Por motivos de cambio de equipo de Desarrollo, la resolución de incidencias está siendo más lenta de lo habitual. Su incidencia está programada entre las tareas de resolución de Inside. Lo sentimos por la tardanza.**

**Comment by ja-garcia** [comment]
Se ha dado de alta una incidencia nueva, [SGAD 627666](https://ssweb.seap.minhap.es/ayuda/seguimiento), porque el error de validación de firma se sigue produciendo en documentos firmados con certificado de ciudadano sin segundo apellido. Hemos aprovechado para pasar en ese nuevo hilo el otro caso relacionado, que nos llegó mediante [GLPI 624799](https://glpi.carm.es/front/ticket.form.php?id=624799). El 10 de enero de 2020 nos han contestado lo siguiente (sobre el hilo de la incidencia 559166):

> Durante el mes de agosto, mes en el que recibimos y detectamos la incidencia que nos han comentado, se desarrolló la solución para que la validación sea correcta. Estamos estudiando de nuevo su caso para comprobar porque sigue dando esté error cuando ya realizamos la pruebas en su momento y todo funcionaba correctamente. Cerramos esta incidencia para tramitar todo el proceso a través de la nueva que han abierto 627666 Disculpe las molestias. Reciba un cordial saludo.

**Comment by ja-garcia** [comment]
El 10 de febrero 2020 notificaron que la incidencia está solucionada a través del ticket [SGAD 627666](https://ssweb.seap.minhap.es/ayuda/seguimiento). 

Se han probado las altas de los dos documentos de los ciudadanos que no se podían guardar como originales en repositorio Inside de la CARM (los respectivos de los tickets GLPI [597760](https://glpi.carm.es/front/ticket.form.php?id=597760) y [624799](https://glpi.carm.es/front/ticket.form.php?id=624799)), tanto contra el endpoint de servicios estables como el de producción, verificando que ya se guardan correctamente.
