### ISSUE TITLE
Dependencia de los WS de las Eutils en el arranque nocturno de INSIDE que causa indisponibilidad prolongada del servicio

### ISSUE THREAD

**Issue by alp23g** [carm-es/inside#20]
Como consecuencia de los reinicios diarios a las 3 am nos encontramos con otro problema grave que sucedió el pasado lunes 8/7/19 del que no nos habíamos dado cuenta antes. INSIDE no funcionó correctamente desde las 3:10 am hasta las 8:48 am. Si en el momento del arranque de la aplicación INSIDE (a las 3 am) no está disponible alguno de los WS de las Eutil que requiere para su funcionamiento, no es capaz de levantarse y el servicio INSIDE se queda indisponible, con lo cual SANDRA no puede darle servicio de repositorio documental a la Sede Electrónica.
Al no poder arrancar el WS correctamente estuvo dando errores **404** que significa "**No se ha encontrado el recurso**" y éste es el mensaje de error de SANDRA: "Error interno de Sandra. -- javax.xml.ws.WebServiceException: Could not send Message. / HTTP response '**404**: 404' when communicating with https://inside.carm.es/inside/ws/InsideUserTokenService -- "
Para acceder a los errores que suceden por este motivo se puede hacer con esta consulta de [Elastic](https://elastic.carm.es/servicios/evento/_search?pretty=true&q=error:S-500%20AND%20texto_mensaje:*404*&size=1000&sort=@timestamp:desc).
Este funcionamiento se podría mejorar incorporando los WSDLs al proyecto tal y como hace PRESENTADOR y SANDRA.

**Comment by aid35y** [comment]
Buenas @ja-garcia

Al intentar consultar los los en corelog, he visto que no existe ninguno el día 8/7/2019. He buscado tanto en **servapp-pro-sa4** como en **servapp-pro-sa3** (que según la traza de Elastic referenciada, son los que estaban fallando).

De hecho, los últimos logs son del 26/03/2019 (tampoco hay ninguno del 2020 para comprobar según el timestamp que se indica en la consulta de Elastic).

¿Cómo podríamos ver estos logs?

Muchas gracias.

Saludos.

**Comment by ja-garcia** [comment]
@aid35y, no guardamos los logs tanto tiempo. La idea es levantar la aplicación en local, deshabilitando las dependencias de los servicios Web externos y comprobar si falla (el método lo dejo a vuestra elección, puede ir desde desconectar la red y levantar la aplicación contra una BD en local hasta usar el archivo *hosts* en local para mapear los dominios externos al *localhost* - se puede utilizar un sniffer de red previamente para ver las conexiones externas que hace la aplicación al arrancarla, que en teoría, es sólo a los servicios de Eeutils ... o cualquier otro método que se os ocurra). 

Una vez reproducido lo anterior, si se comprueba que efectivamente hay dependencias de servicios Web externos, que cuando no están disponibles provocan que la aplicación no despliegue correctamente, queremos conseguir que despliegue el war aunque no estén operativas esas dependencias externas.

**Comment by aid35y** [comment]
Buenos días @ja-garcia

He realizado la prueba que comentas, tirando contra la base de datos en local junto con las llamadas a las eeutils de desarrollo y desconectando la red tanto antes de arrancar el Tomcat como una vez arrancado. En ambas situaciones consigo levantar INSIDE y por lo tanto no puedo reproducir el error que comentas. También he probado a quitar la VPN e incluso la red Wifi y el resultado es el mismo.

Los errores que se muestran son los correspondientes a las eeutils, es decir, al llamar por ejemplo al **vis-docexp** se produce _Failed to create service._ Al llamar al **misc** se produce el error _Problem parsing 'http://eeutil-misc.preappjava.seap.minhap.es/eeutil-misc/ws/EeUtilValidacionENIServiceMtom?wsdl'_ indicándonse el mensaje web: _Error al obtener los datos del WS_ o algo así.

En resumen, los errores que dan es normal que ocurran ya que no había red. Pero **INSIDE** he podido desplegarlo sin problemas entrando por cl@ve (por certificado depende de **oper-firma**)

¿Cómo se procede entonces?

Muchas gracias.

Saludos.

**Comment by ja-garcia** [comment]
Hola @aid35y. La prueba que has hecho es lo que buscamos, seguramente achacamos este problema a las dependencias de las Eeutils y el origen era otro. ¿Puedes repetir la misma prueba y, tras obtener ese error *Failed to create service*, habilitar la conexión de red y la VPN, para comprobar si, tras recuperar la conectividad a las Eeeutils, la aplicación se recupera bien (funcionan las operaciones de los Servicios Web que hacen uso de Eeutils) sin tener que redesplegarla o reiniciar el contenedor de aplicaciones?.

**Comment by aid35y** [comment]
Buenas @ja-garcia.

Ya he realizado la prueba que comentas y ha funcionado todo correctamente, sin tener que levantar el servidor de nuevo, simplemente estableciendo de nuevo la conexión a la red y a la VPN.

He realizado dos pruebas, una llamando a las operaciones de **eeutil-misc** y otra a las de **eeutil-vis-docexp** . Adjunto capturas de lo que indico, donde se puede ver que da fallos al no tener red (Capturas 1, 2 y 3) y el resultado al volver a conectar la red (Captura 4).

Por lo tanto, el error que dió en 2019 lo mismo ocurrió por otra cosa (lo desconozco ya que no aparecen los logs de esa fecha).

Muchas gracias.

Saludos.

![Captura1](https://user-images.githubusercontent.com/75123456/107351024-6972c780-6aca-11eb-8f5a-2ea180277044.PNG)



![Captura2](https://user-images.githubusercontent.com/75123456/107351018-68419a80-6aca-11eb-8d0a-61eb61291730.PNG)



![Captura3](https://user-images.githubusercontent.com/75123456/107351020-68da3100-6aca-11eb-8b6a-50bfa600af35.PNG)



![Captura4](https://user-images.githubusercontent.com/75123456/107351023-6972c780-6aca-11eb-9027-04a0c596e188.PNG)

**Comment by ja-garcia** [comment]
Correcto @aid35y. Con estas últimas verificaciones, doy por cerrado el issue. 
Se confirma que las dependencias de Eeutils no son la causa de la indisponibilidad prolongada y que el reinicio no es necesario. Gracias.
