### ISSUE TITLE
CXF y WSS4J - minor upgrade

### ISSUE THREAD

**Issue by ja-garcia** [carm-es/inside#71]
Actualizar **CXF a la versión mínima 2.17.8** (la dependencia de **WSS4J se actualizará, de manera transitiva, a la versión 1.6.19**).
Actualmente el proyecto tiene dependencias con CXF 2.6.1 y, de manera transitiva, con WSSJ4 1.6.6.

Además de los CVEs reportados para las versiones previas, el origen del cambio viene por errores muy puntuales, en algún nodo del entorno productivo al reiniciar, que provoca indisponibilidad constante de las operaciones de los WS de Inside, con causa raíz:
```
General security error (WSSecurityEngine: No password callback supplied)
```
Cuando se produce este fallo, se está solucionando temporalmente con otro reinicio del contenedor de aplicaciones. Tras la [revisión técnica realizada](https://gitlab.carm.es/SIAC/PAECARM/inside/-/issues/10), sobre el fallo en cuestión, optamos por el upgrade de las versiones de las librerías relacionadas para observar el comportamiento del servicio en los próximos reinicios.

**Comment by MAR63A** [comment]
Buenas tardes,

Ya se ha realizado los cambios para actualizar CXF y WSS4J y subidos a la nueva Rama  #bug/mar63A-Getronics/CXF_WSS4J_minor_upgrade-#71 .

Un Saludo.

**Comment by ja-garcia** [comment]
Hola @MAR63A, la rama que has preparado no parte de la última versión de `develop` (está 4 commits por detrás, tendrías que descargar los últimos cambios y hacerte un `rebase`, para entregar aplicando el commit que has añadido, por encima de los cambios que te faltan). 

Entiendo que has probado que compila con el upgrade de librerías, ¿pero has levantado la aplicación y ejecutado alguna prueba (interfaz web y servicios web)?... me vale con que las comentes por encima, no hace falta poner por aquí las peticiones (el endpoint `InSideUserTokenWebService` es el que más estamos usando, desde los clientes CARM que usan Inside).

**Comment by MAR63A** [comment]
Buenos días @ja-garcia ,

he creado de nuevo la rama, partiendo de la develop, anteriormente lo hice desde la master. Ya anteriormente probamos que la aplicación web funcionase bien. Ahora hemos realizado las prueba de nuevo, funcionando la web correctamente, mientras los servicios web que indicáis( InsideUserTokenService), nos da problemas de credenciales al ejecutarlo, incluso en desarrollo. es normal ya que no disponemos de un token de pruebas.

Es por esta razón por lo que, hemos probado los servicios web de InsideService en lugar de los de InsideUserTokenService. Las pruebas han sido correctas, se ha comprobado varios métodos del Servicio(altaDocumentosOtros,VisualizaciónDocumentos,getExpediente,getDocumento,etc.) y todos han funcionado correctamente.

Un Saludo.

**Comment by ja-garcia** [comment]
Hola @MAR63A. Ya están desplegados los cambios en desarrollo y pruebas.

El token para atacar al endpoint `InSideUserTokenWebService` es de tipo *Username* y sí lo puedes configurar desde SoapUI:

![InsideUserTokenServiceWssConfig](https://user-images.githubusercontent.com/34572356/110094950-afa30a00-7d9c-11eb-89b0-05c6196dcb06.jpg)

**Comment by MAR63A** [comment]
Buenas tardes @ja-garcia ,

He probados los Servicios web de InsideUserTokenWebService con la configuración que me indicabas y las pruebas han sido correctas en DESARROLLO. Hemos probado varios Servicios correctamente y el funcionamiento de la aplicación Web en DESARROLLO también es correcto.

Un Saludo.

**Comment by ja-garcia** [comment]
El testing en el entorno de pruebas es correcto y se puede incluir el cambio en la próxima release.
