### ISSUE TITLE
Integrar en el repositorio la versión 2.0.8.3 (agosto 2018) de inside

### ISSUE THREAD

**Issue by ibarrancos** [carm-es/inside#9]
En agosto 2018 el CTT liberó una nueva versión distribuible de INSIDE: 
- https://administracionelectronica.gob.es/ctt/resources/Soluciones/323/Descargas/inside-src-2-0-8-3-rev2.zip?idIniciativa=323&idElemento=14111

La adaptación completa para obtener la versión 2.0.8.3-CARM.x va a requerir, partiendo de la versión 2.0.8.3 distribuible:
*  **Recepción de la versión distribuible 2.0.8.3** (quedará un histórico de esta recepción en la rama `original_2.0.8` de nuestro repositorio, para tenerla como referencia para futuras actualizaciones a nuevas versiones distribuibles).
*  **Retocar la versión original 2.0.8.3 para poder iterar con los procesos de integración continua de la CARM**. Estos cambios, y los de los siguientes puntos, ya se aplicarán sobre la rama `develop`, partiendo de la versión `original_2.0.8`.
*  **Reaplicación de los parches de la CARM que se han ido incorprando a la 2.0.7-CARM.x**, teniendo en cuenta que podemos ignorar la reaplicación de los parches referentes al conector CMIS, puesto que ya estamos utilizando desde INSIDE los servicios del componente [CSV Storage](https://github.com/carm-es/csvstorage) para el almacenamiento de documentos ENI (es la alternativa disponible al uso de un repositorio documental tipo Alfresco o SharePoint).
*  **Ajustar referencias a fichero de configuración** `enhanced_2-0-7-x.properties`, añadido para configurar los parches que se han ido aplicando en la CARM, para renombrarlo como `enhanced_carm.properties` (de esta manera no se conserva referencia al número de versión, que pudiera llevar a confusión).
*  Llevar la rama `develop` a `master`, renombrando previamente la rama `master` como `carm-2.0.7`.
*  Añadir la nueva rama `develop` que parte de `master` y definirla como la rama por defecto, para seguir la [estrategia de flujo de trabajo OneFlow](https://github.com/carm-es/guias/blob/master/java/Guia-Workflow.md#el-flujo-de-trabajo) definida en la guía.

El changeLog publicado para la nueva versión distribuible 2.0.8.3 incluye:

## Versión 2.0.8.3
**Correcciones:**
* Se mejoran descriptivos en fichero de propiedades csvstorage.properties.
* Script BBDD: Se incluye inserción en tabla InidadWsAplicacion. 

## Versión 2.0.8.2
**Correcciones:**
* Se incluyen propiedades storage.cmis.storeSign y storage.cmis.dir3Default en fichero de propiedades server.cmis.properties 

## Versión 2.0.8
**Modificaciones, correcciones y novedades:**
* Se incluye validación esquema ENI sin necesidad de conexión con eeutils (sí necesario para firmas y comprobar firmas)
* Modificación para evitar clickear varias veces un boton descargas 
* No permitir carpetas vacias por servicio web 
* Nueva operación servicio web: getPdfExpedientePorId
* Se admiten ficheros grandes sin firmar y tipo otros 		
* Admitir ficheros firmados con firmas invalidas por certificado caducado solamente.
* Correcciones validación Enis externos a Inside
* Versionado expedientes al generar credenciales de acceso
* Posibilidad de firma de documentos pdf con cades detached
* Se corrige combo al adjuntar documento Inside
* Se corrige problema metadatos adicionales en documento
* Se permite búsqueda por metadatos adicionales en documentos almacenados 
* Se corrige logado por certificado 
* Se soluciona error al adjuntar documento a expediente
* Se añade al crear expedientes y documentos los DIR3 extinguidos
* Se habilita botón nuevo documento desde expedientes 
* Se impide, en el índice al crear o editar expedientes, crear carpetas o documentos dentro de un documento 
* Se bloquean, en el índice al crear o editar expedientes, los botones de barra superior mientras se adjunta documento inside 
* Debido a que se usa el nombre natural en el índice se modifica los metadatos adicionales, tanto de  Expedientes como de Documentos, para no permitir más de un valor. Esto evita que aparezcan distintos valores en el índice cada vez que se edita un Expediente 
* Se modifica mensaje de error al guardar expediente indicando que debe comprobar si hay carpetas vacías 
* Se deshabilita botones superiores al crear carpetas en el indice de los expedientes 	
* Se elimina error operación convertirDocumentoAEni y convertirDocumentoAEniConMAdicionales al meter el campo contenido vacío.
* Añadir nombre natural al índice del expediente electrónico 
* Gestionar los errores de tuberia rota y connection reset con cache socketexception 
* Corrección de operación convertirExpedienteEni, valida correctamente los elementos dentro de carpetas
* Redirección a login cuando la sesión ha expirado y se realiza llamadas ajax 
* Cambio en el tamaño permitido del campo valor de metadatos adicionales 
* Opción firma longeva de expedientes y documentos, en firma en cliente, en servidor y en documentos anteriormente firmados
* Mejoras spring security 
* Indicador al usuario de que la tarea está en progreso 
* Incidencia dir3 desaparecido, se añade operación en servicio de administración que permite la actualización de dir3 desde una fecha a día de hoy 
* Se incluye clase validación nif, cif y nie
* Corrección error de web service desvincularDocumentosEnExpediente, se añade firma en servidor y se evita que el expediente quede vacío 
* Corrección mal funcionamiento de web service vincularDocumentosEnExpediente, se evita añadir documentos repetidos al expediente 
* Se corrige problema visualizar con internet explorer 
* Incluir en el metadato TipoDocumental de documento el valor TD99- Otros

**Comment by ja-garcia** [comment]
Archivada la última evolución de la versión 2.0.7 como rama `carm-2.0.7`.

A partir de este momento la evolución de la versión 2.0.8.3 (último distribuible liberado hasta el momento) sigue la estrategia OneFlow con la variante `develop + master`.
